AllCops:
  Exclude:
    - 'screencast.rb'
    - 'sandbox.rb'
    - 'string.rb'
    - 'seed.rb'
    - 'metaprogramming.rb'
    - 'send.rb'
    - 'valid.rb'

Lint/RedundantStringCoercion:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false